"""initial migration

Revision ID: 36f173e1e64a
Revises: 
Create Date: 2024-09-13 13:24:27.440648

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '36f173e1e64a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Teams', schema=None) as batch_op:
        batch_op.alter_column('team_id',
               existing_type=mysql.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('team_name',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('country',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=50),
               existing_nullable=True)

    with op.batch_alter_table('Teams_Icons', schema=None) as batch_op:
        batch_op.alter_column('team_id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=36),
               nullable=False)
        batch_op.alter_column('icon_name',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('upload_date',
               existing_type=mysql.DATETIME(),
               type_=sa.Date(),
               existing_nullable=False)

    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notif_count', sa.Integer(), nullable=True))
        batch_op.alter_column('salt',
               existing_type=mysql.TINYBLOB(),
               type_=sa.LargeBinary(length=16),
               existing_nullable=False)
        batch_op.alter_column('hashed_password',
               existing_type=mysql.TINYBLOB(),
               type_=sa.LargeBinary(length=32),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.alter_column('hashed_password',
               existing_type=sa.LargeBinary(length=32),
               type_=mysql.TINYBLOB(),
               existing_nullable=False)
        batch_op.alter_column('salt',
               existing_type=sa.LargeBinary(length=16),
               type_=mysql.TINYBLOB(),
               existing_nullable=False)
        batch_op.drop_column('notif_count')

    with op.batch_alter_table('Teams_Icons', schema=None) as batch_op:
        batch_op.alter_column('upload_date',
               existing_type=sa.Date(),
               type_=mysql.DATETIME(),
               existing_nullable=False)
        batch_op.alter_column('icon_name',
               existing_type=sa.String(length=100),
               type_=mysql.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('team_id',
               existing_type=sa.String(length=36),
               type_=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('Teams', schema=None) as batch_op:
        batch_op.alter_column('country',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('team_name',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('team_id',
               existing_type=mysql.INTEGER(),
               nullable=True,
               autoincrement=True)

    # ### end Alembic commands ###
