"""added the image url column

Revision ID: e589f8f742df
Revises: 36f173e1e64a
Create Date: 2024-09-13 13:35:14.396949

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e589f8f742df'
down_revision = '36f173e1e64a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Teams', schema=None) as batch_op:
        batch_op.alter_column('team_id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)

    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.Text(), nullable=False))
        batch_op.alter_column('salt',
               existing_type=mysql.TINYBLOB(),
               type_=sa.LargeBinary(length=16),
               existing_nullable=False)
        batch_op.alter_column('hashed_password',
               existing_type=mysql.TINYBLOB(),
               type_=sa.LargeBinary(length=32),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.alter_column('hashed_password',
               existing_type=sa.LargeBinary(length=32),
               type_=mysql.TINYBLOB(),
               existing_nullable=False)
        batch_op.alter_column('salt',
               existing_type=sa.LargeBinary(length=16),
               type_=mysql.TINYBLOB(),
               existing_nullable=False)
        batch_op.drop_column('image_url')

    with op.batch_alter_table('Teams', schema=None) as batch_op:
        batch_op.alter_column('team_id',
               existing_type=sa.String(length=36),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
